import { ImageS3Link } from "@/configs/constants";

export enum IconToken {
  BAJAJ = "BAJAJ",
  TOPSECTIONIMAGE1 = "TOPSECTIONIMAGE1",
  WHATSAPP = "WHATSAPP",
  GOLDEN_SHIELD = "GOLDEN_SHIELD",
  VOLT_PARTNER = "VOLT_PARTNER",
  VOLT_ICON = "VOLT_ICON",
  INVESTOR_HERO_IMAGE1_MOB = "INVESTOR_HERO_IMAGE1_MOB",
  INVESTOR_HERO_IMAGE1_WEB = "INVESTOR_HERO_IMAGE1_WEB",
  BAJAJ_PARTNER = "BAJAJ_PARTNER",
  CAMS_PARTNER = "CAMS_PARTNER",
  KFINTECH_PARTNER = "KFINTECH_PARTNER",
  NSDL_PARTNER = "NSDL_PARTNER",
  DIGILOCKER_PARTNER = "DIGILOCKER_PARTNER",
  CERSAI_PARTNER = "CERSAI_PARTNER",
  SIGN_UP_ICON = "SIGN_UP_ICON",
  PLEDGE_ICON = "PLEDGE_ICON",
  KYC_ICON = "KYC_ICON",
  WITHDRAW_ICON = "WITHDRAW_ICON",
  N1_1 = "N1_1",
  N1_2 = "N1_2",
  N1_3 = "N1_3",
  N1_4 = "N1_4",
  VOLT_BENEFIT_IMAGE1 = "VOLT_BENEFIT_IMAGE1",
  PERCENTAGE_1 = "PERCENTAGE_1",
  RUPEE_1 = "RUPEE_1",
  CLOCK_1 = "CLOCK_1",
  SECURE_1 = "SECURE_1",
  ELIGIBLE_1_WEB = "ELIGIBLE_1_WEB",
  ELIGIBLE_1_MOB = "ELIGIBLE_1_MOB",
  BLUE_TICK = "BLUE_TICK",
  GET_IT_ON_GOOGLE = "GET_IT_ON_GOOGLE",
  GET_IT_ON_IOS = "GET_IT_ON_IOS",
  VOLT_APP_QR_CODE = "VOLT_APP_QR_CODE",
  IPHONE_DOUBLE_MOCK = "IPHONE_DOUBLE_MOCK",
  CHEVRON_DOWN = "CHEVRON_DOWN",
  CHEVRON_UP = "CHEVRON_UP",
  VOLT_ICON_WHITE = "VOLT_ICON_WHITE",
  TWITTER = "TWITTER",
  INSTAGRAM = "INSTAGRAM",
  LINKED_IN = "LINKED_IN",
  STARTUP_INDIA = "STARTUP_INDIA",
  DPIIT = "DPIIT",
  THREE_BAR = "THREE_BAR",
  WHATSAPP_STICKY = "WHATSAPP_STICKY",
  VOLT_PARTNER_1 = "VOLT_PARTNER_1",
  GOLDEN_SHIELD_1 = "GOLDEN_SHIELD_1",
  PARTNER_HERO_SECTION = "PARTNER_HERO_SECTION",
  BAJAJ_PARTNER_1 = "BAJAJ_PARTNER_1",
  GREEN_CANCEL = 'GREEN_CANCEL',
  GREEN_SHIELD = 'GREEN_SHIELD',
  GREEN_RUPEE = 'GREEN_RUPEE',
  GREEN_CONTACT = 'GREEN_CONTACT',
  GREEN_PERCENTAGE = 'GREEN_PERCENTAGE',
  GREEN_CLOCK = 'GREEN_CLOCK',
  HOW_IT_WORKS_IMAGE_PARTNER_1 = 'HOW_IT_WORKS_IMAGE_PARTNER_1',
  HOW_IT_WORKS_IMAGE_PARTNER_2 = 'HOW_IT_WORKS_IMAGE_PARTNER_2',
  HOW_IT_WORKS_IMAGE_PARTNER_3 = 'HOW_IT_WORKS_IMAGE_PARTNER_3',
  HOW_IT_WORKS_IMAGE_PARTNER_4 = 'HOW_IT_WORKS_IMAGE_PARTNER_4',
  LEFT_GREY = 'LEFT_GREY',
  LEFT_BLACK = 'LEFT_BLACK',
  RIGHT_GREY = 'RIGHT_GREY',
  RIGHT_BLACK = 'RIGHT_BLACK'
}

export type IconRegistryType = {
  [key in IconToken]: string;
};

export const Icons: IconRegistryType = {
  [IconToken.BAJAJ]: "../../public/images/BajajFinserv.svg",
  [IconToken.GOLDEN_SHIELD]: "/images/GoldenShield.svg",
  [IconToken.TOPSECTIONIMAGE1]: "/images/topSectionImage1.svg",
  [IconToken.VOLT_PARTNER]: "/images/topSectionImage1.svg",
  [IconToken.WHATSAPP]: `${ImageS3Link}/Whatsapp.svg`,
  [IconToken.VOLT_ICON]: `${ImageS3Link}/VoltBlue.svg`,
  [IconToken.INVESTOR_HERO_IMAGE1_MOB]: `${ImageS3Link}/manHoldingPhoneMobile.png`,
  [IconToken.INVESTOR_HERO_IMAGE1_WEB]: `${ImageS3Link}/manHoldingPhoneWeb.png`,
  [IconToken.BAJAJ_PARTNER]: `${ImageS3Link}/bajajPartner.svg`,
  [IconToken.CAMS_PARTNER]: `${ImageS3Link}/CamsPartner.svg`,
  [IconToken.KFINTECH_PARTNER]: `${ImageS3Link}/KfintechPartner.svg`,
  [IconToken.NSDL_PARTNER]: `${ImageS3Link}/NsdlPartner.svg`,
  [IconToken.DIGILOCKER_PARTNER]: `${ImageS3Link}/DigilockerPartner.svg`,
  [IconToken.CERSAI_PARTNER]: `${ImageS3Link}/CersaiPartner.svg`,
  [IconToken.SIGN_UP_ICON]: `${ImageS3Link}/SignUpIcon.svg`,
  [IconToken.PLEDGE_ICON]: `${ImageS3Link}/PledgeIcon.svg`,
  [IconToken.KYC_ICON]: `${ImageS3Link}/KycIcon.svg`,
  [IconToken.WITHDRAW_ICON]: `${ImageS3Link}/WithdrawIcon.svg`,
  [IconToken.N1_1]: `${ImageS3Link}/01_1.svg`,
  [IconToken.N1_2]: `${ImageS3Link}/02_1.svg`,
  [IconToken.N1_3]: `${ImageS3Link}/03_1.svg`,
  [IconToken.N1_4]: `${ImageS3Link}/04_1.svg`,
  [IconToken.VOLT_BENEFIT_IMAGE1]: `${ImageS3Link}/personHoldingPhone1.png`,
  [IconToken.PERCENTAGE_1]: `${ImageS3Link}/percentageVector1.svg`,
  [IconToken.RUPEE_1]: `${ImageS3Link}/rupeeVector1.svg`,
  [IconToken.CLOCK_1]: `${ImageS3Link}/clock1.svg`,
  [IconToken.SECURE_1]: `${ImageS3Link}/secure1.svg`,
  [IconToken.ELIGIBLE_1_WEB]: `${ImageS3Link}/low_cibil_score_web1.png`,
  [IconToken.ELIGIBLE_1_MOB]: `${ImageS3Link}/low_cibil_score1.png`,
  [IconToken.BLUE_TICK]: `${ImageS3Link}/blueCheck1.svg`,
  [IconToken.GET_IT_ON_GOOGLE]: `${ImageS3Link}/getItOnGoogle.svg`,
  [IconToken.GET_IT_ON_IOS]: `${ImageS3Link}/downloadOnAppStore.svg`,
  [IconToken.VOLT_APP_QR_CODE]: `${ImageS3Link}/voltAppQrCode.svg`,
  [IconToken.IPHONE_DOUBLE_MOCK]: `${ImageS3Link}/iPhoneDoubleStylizedMockup.svg`,
  [IconToken.CHEVRON_DOWN]: `${ImageS3Link}/chevron-down.svg`,
  [IconToken.CHEVRON_UP]: `${ImageS3Link}/chevron-up1.svg`,
  [IconToken.VOLT_ICON_WHITE]: `${ImageS3Link}/VoltIcon.svg`,
  [IconToken.TWITTER]: `${ImageS3Link}/twitter.svg`,
  [IconToken.INSTAGRAM]: `${ImageS3Link}/Instagram.svg`,
  [IconToken.LINKED_IN]: `${ImageS3Link}/LinkedIn.svg`,
  [IconToken.STARTUP_INDIA]: `${ImageS3Link}/startUpIndia.svg`,
  [IconToken.DPIIT]: `${ImageS3Link}/startUpRegistration.svg`,
  [IconToken.THREE_BAR]: `${ImageS3Link}/ThreeBar.svg`,
  [IconToken.WHATSAPP_STICKY]: `${ImageS3Link}/whatappSticky.svg`,
  [IconToken.VOLT_PARTNER_1]: `${ImageS3Link}/VoltPartnerLogo.svg`,
  [IconToken.GOLDEN_SHIELD_1]: `${ImageS3Link}/GoldenShield.svg`,
  [IconToken.PARTNER_HERO_SECTION]: `${ImageS3Link}/hero_section_image.png`,
  [IconToken.BAJAJ_PARTNER_1]: `${ImageS3Link}/BajajFinserv.svg`,
  [IconToken.GREEN_CANCEL]: `${ImageS3Link}/greenCancel.svg`,
  [IconToken.GREEN_SHIELD]: `${ImageS3Link}/greenShield.svg`,
  [IconToken.GREEN_RUPEE]: `${ImageS3Link}/greenRupees.svg`,
  [IconToken.GREEN_CONTACT]: `${ImageS3Link}/greenContact.svg`,
  [IconToken.GREEN_PERCENTAGE]: `${ImageS3Link}/greenPercentage.svg`,
  [IconToken.GREEN_CLOCK]: `${ImageS3Link}/greenClock.svg`,
  [IconToken.HOW_IT_WORKS_IMAGE_PARTNER_1]: `${ImageS3Link}/howItWorksImage1.svg`,
  [IconToken.HOW_IT_WORKS_IMAGE_PARTNER_2]: `${ImageS3Link}/howItWorksImage2.svg`,
  [IconToken.HOW_IT_WORKS_IMAGE_PARTNER_3]: `${ImageS3Link}/howItWorksImage3.svg`,
  [IconToken.HOW_IT_WORKS_IMAGE_PARTNER_4]: `${ImageS3Link}/howItWorksImage4.svg`,
  [IconToken.LEFT_GREY]: `${ImageS3Link}/leftGrey.svg`,
  [IconToken.LEFT_BLACK]: `${ImageS3Link}/leftBlack.svg`,
  [IconToken.RIGHT_GREY]: `${ImageS3Link}/rightGrey.svg`,
  [IconToken.RIGHT_BLACK]: `${ImageS3Link}/rigthBlack.svg`,
};
