import Head from "next/head";
// import Image from 'next/image'
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import PartnerLandingPage from "@/LandingPage/PartnerLandingPage";
import {handleWhatAppClick, isMobile} from "@/configs/utils";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  return (
    <>
      <Head>
        <title>Volt Partner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main style={{
            width: '100%'
      }} className={styles.main}>
        <PartnerLandingPage />
          <div className={styles.whatAppStickyMobileContainerHeader} onClick={()=>handleWhatAppClick()}>
              <Image width = {75} height = {75}  src={'./images/whatappSticky.svg'} alt="whatapp sticky mobile"/>
          </div>
      </main>
    </>
  );
}
